### ISSUE TITLE
Issues with Extract-text-plugin for css

### ISSUE THREAD

**Issue by jeffling** [soundcloud/split-by-name-webpack-plugin#2]
Hey, I can't seem to get extract-text-plugin working with split-by-name plugin. 

Here is a stack trace. There is one of these for each module that requires css from a bower component. 

```

ERROR in ./bower_components/selectize/dist/css/selectize.css
Module build failed: TypeError: Cannot call method 'call' of undefined
  at __webpack_require__ (/Users/jeff/Work/benchception/rind/git/node_modules/css-loader/index.js?sourceMap!/Users/jeff/Work/benchception/rind/git/node_modules/autoprefixer-loader/index.js!/Users/jeff/Work/benchception/rind/git/bower_components/selectize/dist/css/selectize.css:27:30)
  at Object.eval (<anonymous>:1:28)
  at Object.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/css-loader/index.js?sourceMap!/Users/jeff/Work/benchception/rind/git/node_modules/autoprefixer-loader/index.js!/Users/jeff/Work/benchception/rind/git/bower_components/selectize/dist/css/selectize.css:69:2)
  at __webpack_require__ (/Users/jeff/Work/benchception/rind/git/node_modules/css-loader/index.js?sourceMap!/Users/jeff/Work/benchception/rind/git/node_modules/autoprefixer-loader/index.js!/Users/jeff/Work/benchception/rind/git/bower_components/selectize/dist/css/selectize.css:27:30)
  at /Users/jeff/Work/benchception/rind/git/node_modules/css-loader/index.js?sourceMap!/Users/jeff/Work/benchception/rind/git/node_modules/autoprefixer-loader/index.js!/Users/jeff/Work/benchception/rind/git/bower_components/selectize/dist/css/selectize.css:62:18
  at Object.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/css-loader/index.js?sourceMap!/Users/jeff/Work/benchception/rind/git/node_modules/autoprefixer-loader/index.js!/Users/jeff/Work/benchception/rind/git/bower_components/selectize/dist/css/selectize.css:65:10)
  at Module._compile (module.js:456:26)
  at Object.loaderContext.exec (/Users/jeff/Work/benchception/rind/git/node_modules/webpack-core/lib/NormalModuleMixin.js:86:7)
  at Object.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/extract-text-webpack-plugin/loader.js:93:22)
  at Tapable.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compiler.js:210:10)
  at /Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compiler.js:398:12
  at Tapable.next (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:11)
  at Object.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/extract-text-webpack-plugin/loader.js:77:5)
  at Tapable.next (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:37)
  at CachePlugin.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/CachePlugin.js:40:4)
  at Tapable.applyPluginsAsync (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/node_modules/tapable/lib/Tapable.js:73:13)
  at Tapable.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compiler.js:395:9)
  at Tapable.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:534:13)
  at Tapable.applyPluginsAsync (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Tapable.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:529:10)
  at Tapable.applyPluginsAsync (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Tapable.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:524:9)
  at Tapable.applyPluginsAsync (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Tapable.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:520:8)
  at Tapable.applyPluginsAsync (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Tapable.seal (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:486:7)
  at Tapable.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compiler.js:392:15)
  at /Users/jeff/Work/benchception/rind/git/node_modules/webpack/node_modules/tapable/lib/Tapable.js:107:11
  at Tapable.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:420:10)
  at Tapable.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:393:12)
  at /Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:315:10
  at done (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/node_modules/async/lib/async.js:135:19)
  at /Users/jeff/Work/benchception/rind/git/node_modules/webpack/node_modules/async/lib/async.js:32:16
  at Tapable.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:220:12)
  at NullFactory.create (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/NullFactory.js:10:9)
  at Tapable.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:203:11)
  at /Users/jeff/Work/benchception/rind/git/node_modules/webpack/node_modules/async/lib/async.js:125:13
  at Array.forEach (native)
  at _each (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/node_modules/async/lib/async.js:46:24)
  at Object.async.each (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/node_modules/async/lib/async.js:124:9)
  at Tapable.Compilation.addModuleDependencies (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:173:8)
  at Tapable.Compilation.processModuleDependencies (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:161:7)
  at Tapable.moduleReady (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:388:9)
  at Tapable.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:383:17)
  at /Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:117:4
  at Array.forEach (native)
  at callback (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:116:12)
  at Tapable.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/Compilation.js:133:10)
  at DependenciesBlock.<anonymous> (/Users/jeff/Work/benchception/rind/git/node_modules/webpack/lib/NormalModule.js:97:10)
  at DependenciesBlock.onModuleBuild (/Users/jeff/Work/benchception/rind/git/node_modules/webpack-core/lib/NormalModuleMixin.js:283:10)
  at nextLoader (/Users/jeff/Work/benchception/rind/git/node_modules/webpack-core/lib/NormalModuleMixin.js:253:25)
  at /Users/jeff/Work/benchception/rind/git/node_modules/webpack-core/lib/NormalModuleMixin.js:270:15
  at runSyncOrAsync (/Users/jeff/Work/benchception/rind/git/node_modules/webpack-core/lib/NormalModuleMixin.js:158:12)
  at nextLoader (/Users/jeff/Work/benchception/rind/git/node_modules/webpack-core/lib/NormalModuleMixin.js:268:3)
  at /Users/jeff/Work/benchception/rind/git/node_modules/webpack-core/lib/NormalModuleMixin.js:270:15
  at Object.context.callback (/Users/jeff/Work/benchception/rind/git/node_modules/webpack-core/lib/NormalModuleMixin.js:146:14)
  at Object.module.exports (/Users/jeff/Work/benchception/rind/git/node_modules/autoprefixer-loader/index.js:43:10)
 @ ./src/ui/form/select/index.coffee 7:0-43
```

I tried using regex to exclude files with .scss. and .css from my bower components bucket, but it didn't seem to work. 

Anybody run in to the same problem?

**Comment by hekike** [comment]
ping, any idea?

**Comment by hekike** [comment]
I've no error simply no css output :)

**Comment by manar-mk** [comment]
I had the same problem, but with bootstrap-loader. Check your entries. I've just disabled the plugin.
